steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sales-predictor', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sales-predictor']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      ['run', 'deploy', 'sales-predictor',
       '--image', 'gcr.io/$PROJECT_ID/sales-predictor',
       '--platform', 'managed',
       '--region', 'us-central1',
       '--allow-unauthenticated']
options:
  logging: CLOUD_LOGGING_ONLY
