# cloudbuild.yaml
# This file defines the CI/CD pipeline for your ML Sales Prediction app.

steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Docker image'
  args:
    - 'build'
    - '-t'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/ml-sales-prediction/sales-predictor:$SHORT_SHA'
    - '.'
  
# Step 2: Push the Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push to Artifact Registry'
  args:
    - 'push'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/ml-sales-prediction/sales-predictor:$SHORT_SHA'

# Step 3: Trigger a Cloud Deploy release (without --target-renders)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Trigger Cloud Deploy Release'
  entrypoint: 'gcloud'
  args:
    - 'deploy'
    - 'releases'
    - 'create'
    - 'sales-predictor-release-$BUILD_ID'
    - '--delivery-pipeline=sales-predictor-pipeline'
    # Removed: - '--target-renders=dev' <-- This line was causing the error
    - '--images=${_SERVICE_NAME}=us-central1-docker.pkg.dev/$PROJECT_ID/ml-sales-prediction/sales-predictor:$SHORT_SHA'
    - '--region=us-central1'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _SERVICE_NAME: sales-predictor-service
