# cloudrun.yaml
# This file defines the Cloud Run service that Cloud Deploy will manage.

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  # IMPORTANT: This name MUST exactly match the _SERVICE_NAME substitution
  # in your cloudbuild.yaml and the left side of the --images flag.
  name: sales-predictor-service
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/ingress: "all" # Allows public access
    spec:
      containers:
      - # Cloud Deploy will inject the image here from your cloudbuild.yaml's --images flag.
        # You can leave this empty, or put a placeholder. Cloud Deploy will override it.
        image:
        ports:
        - containerPort: 8080 # Your Flask app runs on port 8080
