# skaffold.yaml
# This file defines the deployment configuration for Cloud Deploy.

apiVersion: skaffold/v4beta7 # Ensure this API version is correct
kind: Config
manifests:
  rawYaml:
    # Point to your Cloud Run service definition file.
    # Ensure this path is correct relative to your skaffold.yaml.
    - path: cloudrun.yaml
