# gke-manifests/deployment.yaml
# Defines the Kubernetes Deployment for your ML Sales Prediction app.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-predictor-deployment # Name of your deployment
  labels:
    app: sales-predictor-app
spec:
  replicas: 1 # Start with one replica
  selector:
    matchLabels:
      app: sales-predictor-app
  template:
    metadata:
      labels:
        app: sales-predictor-app
    spec:
      containers:
      - name: sales-predictor-container # Name of the container
        # IMPORTANT: Corrected image path with existing tag
        image: us-central1-docker.pkg.dev/faa-gcp-training-14-kfa-0808/ml-sales-prediction/sales-predictor:5dda483 # <-- CHANGED THIS LINE
        ports:
        - containerPort: 8080 # Your Flask app's port
        env:
        - name: PORT # Cloud Run often uses PORT, GKE also respects it
          value: "8080"